name: Generator CI
on: [push, pull_request]
jobs:
    generator-jhipster-quarkus:
        name: npm test
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
        timeout-minutes: 20
        strategy:
            fail-fast: false
            matrix:
                node_version: [14.15.0]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Run git history
              run: git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) <%an>%Creset' --abbrev-commit
            - run: npm ci
            - run: npm test
